package com.eventorganizer.exceptions;

public enum ErrorCode {
    ERR_AUTH_INVALID_CREDENTIALS,
    ERR_AUTH_DUPLICATE_USERNAME,
    ERR_AUTH_DUPLICATE_EMAIL,
    ERR_VALIDATION,
    ERR_USER_NOT_FOUND,
    ERR_EVENT_NOT_FOUND,
    ERR_INVITATION_NOT_FOUND,
    ERR_UNAUTHORIZED,
    ERR_CONFLICT_INVITATION,
    ERR_CONFLICT_FRIEND_REQUEST,
    ERR_INVALID_OPERATION
}
